# Project information
site_name: SCUT-BDA Wiki
site_description: 华南理工大学大数据应用协会
site_author: SCUT BigData Association
site_url: 'https://bda-scut.github.io/BDA-wiki/'

# Repository
repo_name: SCUT-BDA/BDA-wiki
repo_url: 'https://github.com/SCUT-BDA/BDA-wiki'

# Copyright
copyright: 'Copyright &copy; 2026 SCUT BigData Association. All rights reserved.' 

# Theme configuration
theme:
  name: material
  language: zh
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.instant
    - content.code.copy
  palette:
    # palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: 切换到暗色模式
    # palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换到亮色模式
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'


# Navigation
nav:
  - 首页: index.md

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML